"""Agent backend interface for the auto-apply stage.

Backends launch an AI coding agent (Grok Build or Claude Code) that drives
Playwright MCP over CDP and must emit RESULT:* lines in their final output.
"""

from __future__ import annotations

import re
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable


# Status strings returned to the launcher (lowercase, launcher-compatible)
RESULT_APPLIED = "applied"
RESULT_EXPIRED = "expired"
RESULT_CAPTCHA = "captcha"
RESULT_LOGIN = "login_issue"
RESULT_SKIPPED = "skipped"


@dataclass
class AgentRunContext:
    """Everything a backend needs to run one job application."""

    job: dict
    prompt: str
    worker_id: int
    cdp_port: int
    worker_dir: Path
    model: str
    dry_run: bool = False
    timeout_seconds: int = 300
    # Optional live progress callback: (description: str) -> None
    on_action: Callable[[str], None] | None = None
    log_path: Path | None = None


@dataclass
class AgentRunResult:
    """Normalized result from any agent backend."""

    status: str  # applied | expired | captcha | login_issue | failed:reason | skipped
    duration_ms: int
    raw_output: str = ""
    cost_usd: float = 0.0
    input_tokens: int = 0
    output_tokens: int = 0
    turns: int = 0
    backend: str = ""
    meta: dict = field(default_factory=dict)


class ApplyBackend(ABC):
    """Pluggable auto-apply agent (Grok Build, Claude Code, …)."""

    name: str = "base"

    @abstractmethod
    def is_available(self) -> bool:
        """True if the CLI/binary for this backend is on PATH."""

    @abstractmethod
    def run(self, ctx: AgentRunContext) -> AgentRunResult:
        """Execute one application attempt and return a normalized result."""

    def default_model(self) -> str:
        return "default"

    def describe(self) -> str:
        return self.name


def parse_result_text(output: str) -> str:
    """Extract RESULT:* status from agent transcript.

    Returns launcher-compatible status strings:
      applied | expired | captcha | login_issue | failed:<reason> | failed:no_result_line
    """
    if not output:
        return "failed:no_result_line"

    def _clean_reason(s: str) -> str:
        return re.sub(r'[*`"]+$', "", s).strip()

    for result_status in ("APPLIED", "EXPIRED", "CAPTCHA", "LOGIN_ISSUE"):
        if f"RESULT:{result_status}" in output:
            return result_status.lower()

    if "RESULT:FAILED" in output:
        for out_line in output.split("\n"):
            if "RESULT:FAILED" not in out_line:
                continue
            # RESULT:FAILED:reason or RESULT:FAILED
            after = out_line.split("RESULT:FAILED", 1)[-1]
            reason = after.lstrip(":").strip() if after else "unknown"
            reason = _clean_reason(reason) or "unknown"
            promote = {"captcha", "expired", "login_issue"}
            if reason in promote:
                return reason
            return f"failed:{reason}"
        return "failed:unknown"

    return "failed:no_result_line"


def make_playwright_mcp_config(cdp_port: int, viewport: str = "1280x900") -> dict:
    """Shared Playwright MCP server config for Claude-style JSON mcp configs."""
    return {
        "mcpServers": {
            "playwright": {
                "command": "npx",
                "args": [
                    "@playwright/mcp@latest",
                    f"--cdp-endpoint=http://localhost:{cdp_port}",
                    f"--viewport-size={viewport}",
                ],
            },
            "gmail": {
                "command": "npx",
                "args": ["-y", "@gongrzhe/server-gmail-autoauth-mcp"],
            },
        }
    }


def make_grok_mcp_toml(cdp_port: int, viewport: str = "1280x900") -> str:
    """Project-scoped Grok MCP config (written to worker_dir/.grok/config.toml)."""
    # TOML: args as array of strings
    return f"""# Auto-generated by ApplyPilot — do not edit by hand
# Playwright MCP attached to Chrome CDP on port {cdp_port}

[mcp_servers.playwright]
command = "npx"
args = [
  "@playwright/mcp@latest",
  "--cdp-endpoint=http://localhost:{cdp_port}",
  "--viewport-size={viewport}",
]
startup_timeout_sec = 120
tool_timeout_sec = 300

[mcp_servers.gmail]
command = "npx"
args = ["-y", "@gongrzhe/server-gmail-autoauth-mcp"]
enabled = true
startup_timeout_sec = 60
"""
